drop table if exists department_domain CASCADE;
drop table if exists task_domain CASCADE;
create table department_domain (id bigint generated by default as identity, name varchar(255), primary key (id));
create table task_domain (id bigint generated by default as identity, desc varchar(255), est_cost double, est_workers integer, name varchar(255) not null, my_department_id bigint not null, primary key (id));
alter table task_domain add constraint FKm3h92g8usym6a0ujsig2qmwde foreign key (my_department_id) references department_domain on delete cascade;